// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6OqklsSFPwy_f93WxRykQYvwdCaSvD9w',
    appId: '1:502137178265:web:74d367ed215c14c699d008',
    messagingSenderId: '502137178265',
    projectId: 'taxi-app-9ed7c',
    authDomain: 'taxi-app-9ed7c.firebaseapp.com',
    storageBucket: 'taxi-app-9ed7c.appspot.com',
    measurementId: 'G-2KQNY4TESL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7OLvvwvVe87hCzMdszy3aSP_hJopc9U',
    appId: '1:502137178265:android:29a5ec55eb41c9e999d008',
    messagingSenderId: '502137178265',
    projectId: 'taxi-app-9ed7c',
    storageBucket: 'taxi-app-9ed7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA35vPi7-ee39sWcMgFDNXopN_-y6M7S2U',
    appId: '1:502137178265:ios:5909b75e3e1e815099d008',
    messagingSenderId: '502137178265',
    projectId: 'taxi-app-9ed7c',
    storageBucket: 'taxi-app-9ed7c.appspot.com',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA35vPi7-ee39sWcMgFDNXopN_-y6M7S2U',
    appId: '1:502137178265:ios:5909b75e3e1e815099d008',
    messagingSenderId: '502137178265',
    projectId: 'taxi-app-9ed7c',
    storageBucket: 'taxi-app-9ed7c.appspot.com',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6OqklsSFPwy_f93WxRykQYvwdCaSvD9w',
    appId: '1:502137178265:web:40d7b9ccaf04ab3399d008',
    messagingSenderId: '502137178265',
    projectId: 'taxi-app-9ed7c',
    authDomain: 'taxi-app-9ed7c.firebaseapp.com',
    storageBucket: 'taxi-app-9ed7c.appspot.com',
    measurementId: 'G-M1Z3P87347',
  );
}
